version: '3'
services:
  nginx:
    build:
      context: docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/app
    ports:
      - 80:80
    depends_on:
      - php
  php:
    build:
      context: docker
      dockerfile: php.dockerfile
    volumes:
      - ./:/app
  db:
    image: 'mysql:5.7.26'
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
  redis:
    image: 'redis:5.0.5-alpine'
  migrations:
    build:
      context: docker
      dockerfile: migrations.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - php
      - db
      - redis

  node:
    image: node:latest
    entrypoint: yarn install
    volumes:
      - ./:/app
  composer:
    image: composer:latest
    entrypoint: composer install --ignore-platform-reqs
    volumes:
      - ./:/app
